# Generated by Django 4.2.1 on 2025-12-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.IntegerField(default=0),
        ),
    ]
