# Generated by Django 4.2.1 on 2025-12-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_watchlist_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
